# Generated by Django 5.2.8 on 2026-02-04 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_batch_topic_classslot_selectedslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
